# Generated by Django 6.0 on 2025-12-12 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otpemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
                ('auth_method', models.CharField(choices=[('email', 'Email'), ('app', 'authenticator app')], default='email', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
