# Generated by Django 5.2.7 on 2025-12-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_otpemail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Otpemail',
            new_name='OTPToken',
        ),
        migrations.AlterModelOptions(
            name='otptoken',
            options={'ordering': ['-created_at']},
        ),
    ]
