# Generated by Django 5.2.7 on 2025-12-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_otpemail_otptoken_alter_otptoken_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otptoken',
            old_name='opt_code',
            new_name='token',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
