# Generated by Django 5.2.8 on 2025-12-19 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_total_alter_orderitem_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
