# Generated by Django 5.2.8 on 2025-12-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default='Item', help_text='e.g. kg, box, pc', max_length=50),
        ),
    ]
