# Generated by Django 5.2.8 on 2025-12-16 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_options_remove_product_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon_class',
        ),
    ]
