# Generated by Django 5.2.8 on 2025-12-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_unit_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('lb', 'Pound (lb)'), ('bag', 'Bag'), ('box', 'Box'), ('liter', 'Liter (L)'), ('ml', 'Milliliter (ml)'), ('pc', 'Piece (pc)'), ('dozen', 'Dozen'), ('pack', 'Pack'), ('meter', 'Meter (m)')], max_length=50, null=True),
        ),
    ]
